version: "3"
services:

    otel-collector:
        image: otel/opentelemetry-collector
        command: ["--config=/etc/otel-collector-config.yaml"]
        extra_hosts: ['host.docker.internal:host-gateway']
        volumes:
        - ./config.yaml:/etc/otel-collector-config.yaml
        ports:
        - "8888:8888"   # Prometheus metrics exposed by the collector
        - "8889:8889"   # Prometheus exporter metrics
        - "9411:9411"   # Prometheus exporter metrics
        - "9090:9090"   # Prometheus exporter metrics

    zipkin-collector:
        image: openzipkin/zipkin
        extra_hosts: ['host.docker.internal:host-gateway']
        ports:
            - 6543:9411

    prometheus-collector:
        image: prom/prometheus
        extra_hosts: ['host.docker.internal:host-gateway']
        command:
            - --enable-feature=exemplar-storage
            - --web.enable-remote-write-receiver
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./docker/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - 5432:9090

    grafana-collector:
        image: grafana/grafana
        extra_hosts: ['host.docker.internal:host-gateway']
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        volumes:
            - ./docker/config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
            - ./docker/config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
        ports:
            - 3000:3000

# Zipkin: http://localhost:9411/zipkin/
# Prometheus: http://localhost:9090/
# Grafana: http://localhost:3000/
